###
https://github.com/jch/html-pipeline/blob/master/lib/html/pipeline/toc_filter.rb
https://gist.github.com/asabaylus/3071099
###
anchor = (heading, headings) ->
  heading
  .trim()
  .toLowerCase()
  .replace /[^\w\- ]/g, ''
  .replace /[ ]/g, '-'
  if headings[heading]
    heading += "-#{headings[heading]++}"
  else
    headings[heading] = 1
  heading

module.exports =
  names: ['github-internal-links']
  description: 'Check internal links like those generated by Github'
  tags: ['links']
  function: ({tokens}, onError) ->
    links = []
    heading = null
    headings = {}
    anchors = {}
    for token in tokens
      switch token.type
        when 'inline'
          for child in token.children
            switch child.type
              when 'link_open'
                for [key, value] in token.attrs
                  if key == 'href' and value?.startsWith '#'
                    links.push value[1..]
              when 'text'
                heading += child.content if heading?
        when 'heading_open'
          heading = ''
        when 'heading_close'
          anchors[anchor heading, headings] = true
          heading = null
    console.log headings
    console.log anchors
    for anchor of anchors
      unless anchor of anchors
        onError "Internal anchor link ##{anchor} does not match any heading"
    undefined
